name: SQL Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres-primary:
        image: postgres:12
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres-replica:
        image: postgres:12
        env:
          POSTGRES_DB: repdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5433
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python tests/test_script.py
          python tests/test_schema_design.py
          python tests/test_acid.py
          python tests/test_replication.py
          python tests/test_attrition.py
          python leetcode/leetcode.py

      - name: Set exit status
        id: set_status
        run: exit 0

      - name: Update README if tests pass
        run: |
          if [ \${{ steps.set_status.outcome }} == 'success' ]; then
            echo 'Tests passing' > README.md
          else
            echo 'Tests failed' > README.md
          fi
        if: always()
